[package]
name = "bea"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "bea"

[features]
api = []

[dependencies]
assert-json-diff = "2.0.2"
bincode = "1.3.3"
clap = { version = "4.5.23", features = ["derive"] }
console = "0.15.10"
convert_case = "0.6.0"
csv = "1.3.1"
derive-getters = "0.5.0"
derive-new = "0.7.0"
derive_more = { version = "1.0.0", features = ["full"] }
derive_setters = "0.1.6"
dotenvy = "0.15.7"
indicatif = { version = "0.17.9", features = ["tokio"] }
jiff = { version = "0.1.21", features = ["serde"] }
nom = "7.1.3"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
similar = { version = "2.6.0", features = ["serde"] }
spreadsheet = { git = "https://github.com/grantspassoregon/spreadsheet.git" }
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }
strum_macros = "0.26.4"
tokio = { version = "1.42.0", features = ["full"] }
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = [
  "registry",
  "env-filter",
] }
url = { version = "2.5.4", features = ["serde"] }

[dev-dependencies]
anyhow = "1.0.95"
